version: 0.0
os: linux
files:
  - source: target/springbootwildfly-0.0.1-SNAPSHOT.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

