version: 0.0
os: linux
files:
  - source: springbootwildfly-0.0.1-SNAPSHOT.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root

