version: 0.0
os: linux
files:
  - source: springbootwildfly-0.0.1-SNAPSHOT.jar
    destination: /tmp
permissions:
  - object: start_server
    mode: 755
    owner: ec2-user
    group: ec2-user    
  - object: stop_server
    mode: 755
    owner: ec2-user
    group: ec2-user    
    
hooks:
  BeforeInstall:
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root

