version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
      - echo $JAVA_HOME
      - export PATH=$JAVA_HOME/bin:$PATH
  pre_build:
    commands:
      - echo "Verificando versión de Java y Maven..."
      - java -version
      - mvn -version
      - echo "Descargando dependencias Maven..."
      - mvn clean install -DskipTests
  build:
    commands:
      - echo "Compilando el proyecto con Maven..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Compilación completada. Preparando artefactos..."
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
